# Site metadata
keywords: Cryptography, Privacy, Security
description: Dr. David Derler | Cryptographer | Engineer | Engineering Leader
title: Professional Website of Dr. David Derler

author: David Derler
authorimg: images/dd.png
authoroccup: Cryptographer | Engineer | Leader

# inst: DFINITY
# insturl: https://www.dfinity.org
# uni: Graz University of Technology
# uniurl: http://www.tugraz.at

vcard: 'mailto:cryptsec@derler.info'
office: https://online.tugraz.at/tug_online/ris.einzelraum?raumkey=4944
twitter: dderler
keybase: dderler
github: derlerd
linkedin: derlerd
dblp: hd/d/Derler:David
scholar: YfMKI0wAAAAJ

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
collections:
  - preprints
  - proc
  - jour
  - articles
  - theses
  - deli
  - talk
exclude:
  - Gemfile
  - Gemfile.lock
include:
  - keybase.txt
